- hosts: all
  tasks:
    - name: install apache2 pour debian
      package:
        name: apache2
      when: ansible_os_family == 'Debian' 

    - name: install httpd pour centos
      package:
        name: httpd
      when: ansible_os_family == 'RedHat'

    - name: Installer quelques dépendances 
      package:
        name: 
          - git

    - name: Démarrage du service
      service:
        name: apache2
        state: started
        enabled: true
      when: ansible_os_family == 'Debian'

    - name: Démarrage du service
      service:
        name: httpd
        state: started
        enabled: true
      when: ansible_os_family == 'RedHat'

    - name: Déploiement site web
      git:
        repo: https://github.com/cloudacademy/static-website-example.git
        dest: /var/www/html/website

    - name: install tomcat pour debian
      package:
        name: tomcat9
      when: ansible_os_family == 'Debian' 

    - name: Démarrage du service
      service:
        name: tomcat9
        state: started
        enabled: true
      when: ansible_os_family == 'Debian'
      
    - reboot:
